### ISSUE TITLE
Adding a timeout on the client side if the server does not send a response

### ISSUE THREAD

**Issue by damartripamungkas** [h-sifat/express-ipc#1]
```javascript
// server.js
const server = new Server({ path: })
server.post("/", ({ req, res }) => {
  if (req.body == "ping") {
    res.send("pong");
  }
})

server.listen({
  path: "./test.ipc",
  callback: () => {
    console.log(`server ipc running`);
  },
});
```

```javascript
// client.js
const client = new Client({ path: "./test.ipc" });
(async () => {
  const run = await client.post("/", {
    body: "anything lorem ipsum",
  });

  console.log({ run });
})();
```

**Comment by h-sifat** [comment]
Seems like a good idea. I'll try to add it this weekend.

By the way, if you don't mind I would love to know what are you using express-ipc for.

**Comment by damartripamungkas** [comment]
> Seems like a good idea. I'll try to add it this weekend.
> 
> By the way, if you don't mind I would love to know what are you using express-ipc for.

This is pretty good for interaction between independently generated processes (child_process:spawn) since node.js doesn't provide it by default

**Comment by h-sifat** [comment]
Hello @damartripamungkas, finally I've published the new feature. Kindly read the [docs](https://github.com/h-sifat/express-ipc#clientrequest) for request methods (`request`, `get`, etc.). Thank you.
